service: serverless-js
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
functions:
  application:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: get
plugins:
  - serverless-offline
